- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*csproj'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    feedsToUse: 'select'
    vstsFeed: '5ecb895e-e68e-4ece-a0ee-8870c3062cae'
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
